### ISSUE TITLE
Unbuffered MySQL connections fail with "Unread result found"

### ISSUE THREAD

**Issue by reissmann** [ddserver/ddserver#79]
When trying to add a new zone, it fails with the following exception:

```
127.0.0.1 - - [04/Jul/2015 20:02:19] "GET /admin/suffixes/add HTTP/1.1" 200 4710
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib64/python3.3/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib64/python3.3/site-packages/require/__init__.py", line 200, in wrapped
    **kwargs)
  File "/home/major/Dev/ddserver/ddserver/interface/user.py", line 163, in wrapped
    **kwargs)
  File "/usr/lib64/python3.3/site-packages/require/__init__.py", line 200, in wrapped
    **kwargs)
  File "/home/major/Dev/ddserver/ddserver/interface/validation.py", line 78, in wrapped
    **kwargs)
  File "/usr/lib64/python3.3/site-packages/require/__init__.py", line 200, in wrapped
    **kwargs)
  File "/home/major/Dev/ddserver/ddserver/interface/pages/admin/suffixes.py", line 98, in post_suffix_add
    ''', {'name': data.suffix_name})
  File "/usr/lib64/python3.3/site-packages/mysql/connector/cursor.py", line 476, in execute
    raise errors.InternalError("Unread result found.")
mysql.connector.errors.InternalError: Unread result found.
127.0.0.1 - - [04/Jul/2015 20:02:21] "POST /admin/suffixes/add HTTP/1.1" 500 2155
```

Interestingly, this does not happen when adding new hostnames, but only when adding zones. 

Setting 

``` python
connection = mysql.connector.connect([...], buffered = True)
```

seems to fix the issue.

**Comment by reissmann** [comment]
When and how was this bug introduced?

**Comment by theshahzaibc** [comment]
All you have to do is pass `buffered = true` in your cursor. Read more official [docs](https://dev.mysql.com/doc/connector-python/en/connector-python-tutorial-cursorbuffered.html)

`cursor = conn.cursor(buffered=True)`
