### ISSUE TITLE
Remove admin privileges does not work

### ISSUE THREAD

**Issue by reissmann** [ddserver/ddserver#87]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle-0.12.9-py2.7.egg/EGG-INFO/scripts/bottle.py", line 862, in _handle
    return route.call(*_args)
  File "/usr/local/lib/python2.7/dist-packages/bottle-0.12.9-py2.7.egg/EGG-INFO/scripts/bottle.py", line 1732, in wrapper
    rv = callback(_a, **ka)
  File "build/bdist.linux-x86_64/egg/require/__init__.py", line 200, in wrapped
    *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ddserver-0.3_dev-py2.7.egg/ddserver/interface/user.py", line 163, in wrapped
    *_kwargs)
  File "build/bdist.linux-x86_64/egg/require/**init**.py", line 200, in wrapped
    *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ddserver-0.3_dev-py2.7.egg/ddserver/interface/validation.py", line 78, in wrapped
    *_kwargs)
  File "build/bdist.linux-x86_64/egg/require/**init**.py", line 200, in wrapped
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ddserver-0.3_dev-py2.7.egg/ddserver/interface/pages/admin/users.py", line 279, in post_user_rmadmin
    ''', { 'user_id': data.user_id})
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
IntegrityError: 1048 (23000): Column 'admin' cannot be null

**Comment by reissmann** [comment]
can't reproduce anymore.
