### ISSUE TITLE
Compatibility with pdns-remotebackend >= 0.7

### ISSUE THREAD

**Issue by reissmann** [ddserver/ddserver#95]
Currently, compatibility with pdns-remotebackend-python >= 0.7 is not given.

````
Jul 21 20:52:26 ddserver pdns_server[4603]: Traceback (most recent call last):
Jul 21 20:52:26 ddserver pdns_server[4603]: File "/opt/ddserver/bin/ddserver-recursor", line 11, in <module>
Jul 21 20:52:26 ddserver pdns_server[4603]: load_entry_point('ddserver==0.3.dev0', 'console_scripts', 'ddserver-recursor')()
Jul 21 20:52:26 ddserver pdns_server[4603]: File "/opt/ddserver/local/lib/python2.7/site-packages/ddserver-0.3.dev0-py2.7.egg/ddserver/recursor/__main__.py", line 140, in main
Jul 21 20:52:26 ddserver pdns_server[4603]: pdns.remotebackend.PipeConnector(DdserverHandler).run()
Jul 21 20:52:26 ddserver pdns_server[4603]: File "/opt/ddserver/local/lib/python2.7/site-packages/Pdns_Remotebackend-0.7-py2.7.egg/pdns/remotebackend/__init__.py", line 190, in run
Jul 21 20:52:26 ddserver pdns_server[4603]: self.mainloop(sys.stdin, sys.stdout)
Jul 21 20:52:26 ddserver pdns_server[4603]: File "/opt/ddserver/local/lib/python2.7/site-packages/Pdns_Remotebackend-0.7-py2.7.egg/pdns/remotebackend/__init__.py", line 62, in mainlo
Jul 21 20:52:26 ddserver pdns_server[4603]: return self.mainloop4(reader, writer, h)
Jul 21 20:52:26 ddserver pdns_server[4603]: File "/opt/ddserver/local/lib/python2.7/site-packages/Pdns_Remotebackend-0.7-py2.7.egg/pdns/remotebackend/__init__.py", line 176, in mainl
Jul 21 20:52:26 ddserver pdns_server[4603]: getattr(h, method)(args)
Jul 21 20:52:26 ddserver pdns_server[4603]: File "/opt/ddserver/local/lib/python2.7/site-packages/ddserver-0.3.dev0-py2.7.egg/ddserver/recursor/__main__.py", line 133, in do_lookup
Jul 21 20:52:26 ddserver pdns_server[4603]: self.answer_a(args['qname'])
Jul 21 20:52:26 ddserver pdns_server[4603]: File "/opt/ddserver/local/lib/python2.7/site-packages/ddserver-0.3.dev0-py2.7.egg/ddserver/recursor/__main__.py", line 89, in answer_a
Jul 21 20:52:26 ddserver pdns_server[4603]: response = self.record_prio_ttl(qname, 'A', host['address'], 0, self.config.dns.ttl)
Jul 21 20:52:26 ddserver pdns_server[4603]: AttributeError: DdserverHandler instance has no attribute 'record_prio_ttl'
````

**Comment by reissmann** [comment]
https://github.com/cmouse/pdns-remotebackend-python/commit/0c7fde032c2d53c6c682d4987770b60435463348
